### ISSUE TITLE
Output BODS data in V0.2

### ISSUE THREAD

**Issue by stevenday** [openownership/register#13]
So that
- It matches the most obvious documentation
- It provides a working example of the current guidance and standard
- We don't have to incur tech debt maintaining multiple versions of parsers, etc

Assumptions
- [ ] We have work to do upgrading our BODS export to match v0.2. In particular, we’re not working to a consistent model of indirect ownership because we’re currently reflecting each individual source’s approach
- [x] We need lib-cove-bods to be updated to v0.2 and released

A/C
- [ ] It's valid according lib-cove-bods
- [ ] - TBC - it matches all the new things in v0.2

**Comment by StephenAbbott** [comment]
Completed in August 2023 https://www.openownership.org/en/news/the-new-open-ownership-register-faster-more-efficient-and-produces-more-detailed-beneficial-ownership-data/
