### ISSUE TITLE
Register v2: Country source/entity labels

### ISSUE THREAD

**Issue by StephenAbbott** [openownership/register#146]
Name of country source and type of entity labels not appearing on prototype pages for entities under the title (compare [this](https://register.openownership.org/entities/6189606bf2e3d5ce5fcfb823) with [this](https://openownership-register-v2-stag.herokuapp.com/entities/6885827946361901249))

**Comment by spacesnottabs** [comment]
https://github.com/openownership/register-v2/pull/2

**Comment by StephenAbbott** [comment]
Tested and signed off ✅
