### ISSUE TITLE
Register v2: Person details repeated

### ISSUE THREAD

**Issue by StephenAbbott** [openownership/register#148]
When you are on a person page in Register v2 and look at the People with similar names section, the [page details you are on](https://openownership-register-v2-stag.herokuapp.com/entities/6468360937103290419) are repeated in that section. Can we hide those repeated details?

**Comment by tiredpixel** [comment]
@spacesnottabs, @StephenAbbott, what is the testing status of this ticket, please?

**Comment by StephenAbbott** [comment]
Tested and signed off ✅
