### ISSUE TITLE
Register v2: Hundreds of PSC identifiers produced for same entity

### ISSUE THREAD

**Issue by spacesnottabs** [openownership/register#153]
When transforming PSC records, some can produce hundreds of unique identifiers using the PSC link URL from the source record.

```
...
{"document_id"=>"GB PSC Snapshot", "link"=>"/company/12728169/persons-with-significant-control/corporate-entity/gSel9kO8D2MHk5upXoFQLSR6zzA", "company_number"=>"09361466"},
 {"document_id"=>"GB PSC Snapshot", "link"=>"/company/12729601/persons-with-significant-control/corporate-entity/srvxdgCRlgLeC6u1cfgRHqgwFf0", "company_number"=>"9361466"},
 {"document_id"=>"GB PSC Snapshot", "link"=>"/company/12731527/persons-with-significant-control/corporate-entity/4UZxvVwxokDJXFx1TZIDCrvV4lU", "company_number"=>"9361466"},
```

The current flow will fetch all previous statements for this entity, append a new identifier, then save a new record, each time it is seen as part of a new statement from the PSC source.
This means for some companies which are involved in a few thousand statements, this would need to fetch thousands of statements and store a new record each time with thousands of identifiers.

To resolve this, do not use the PSC statement link as an identifier and instead use it to populate the source.url of the produced BODS v0.2 record.

**Comment by tiredpixel** [comment]
@StephenAbbott, @spacesnottabs, if I understand correctly, this has passed testing. Is it ready to be closed?
