### ISSUE TITLE
Display Legal Entity Identifier (LEI) where available for companies

### ISSUE THREAD

**Issue by StephenAbbott** [openownership/register#160]
Once work on https://github.com/openownership/register-sources-oc/issues/8 is complete, we should update https://github.com/openownership/register-v2 to display the LEIs where available in the company information column to the right of the beneficial ownership details on entity pages as well as providing a link to LEI record on GLEIF's website so people can see the level 2 data associated with that entity - e.g. https://search.gleif.org/#/record/254900Q1X2YV10572B76

**Comment by tiredpixel** [comment]
Once the linked PRs are merged, this can be tested.

**Comment by tiredpixel** [comment]
@StephenAbbott, this is deploy to stg and is now ready for testing.

**Comment by StephenAbbott** [comment]
Thanks @tiredpixel. Happy to sign this one off as I've just tested a bunch of entities. Can you close ticket?

**Comment by tiredpixel** [comment]
That's great. Thanks, @StephenAbbott .
