### ISSUE TITLE
OpenCorporates Reconciliation API

### ISSUE THREAD

**Issue by spacesnottabs** [openownership/register#161]
The OpenCorporates Reconciliation API has changed to only allow whitelisted IP addresses.

https://github.com/openownership/register/blob/master/app/clients/reconciliation_client.rb

For our BODS v2 transformers, this is fine as OpenCorporates has whitelisted the IP for our EC2 instance which runs the transformers.

However, our Register v1 importers run on Heroku, which don’t provide us with the IP address of the dynos which run the imports.

It may be possible to update our code to use the normal OpenCorporates API to reconcile company numbers, using the endpoint for searching companies, as that also searches by company name and jurisdiction code:

https://api.opencorporates.com/documentation/API-Reference#get-companies/search

This will need to be compared to see if it gives the right results and what the differences are between this and the Reconciliation API.

Note: it will probably be necessary for the dev’s local IP to be added by OpenCorporates to be able to properly compare these.

**Comment by StephenAbbott** [comment]
@spacesnottabs Response received on this from OpenCorporates helpdesk:

> OpenCorporates have applied IP restrictions to the reconciliation API and in parallel removed unauthenticated access to its standard API offering. This was enacted to address widespread abuse of the system by anonymous third parties. While the standard API provides an authentication mechanism via API key, this is not supported by the reconciliation API and therefore we have opted for IP whitelisting.
> 
> We can whitelist access to the reconciliation API when a client provides their IP address or appropriate range.
> 
> Static IP addresses, from within environments like Heroku, AWS, Azure or GCP can be achieved using various techniques from NAT Gateway, VPN + NAT Gateway or even third-party services.
> 
> AWS NAT Gateway (https://docs.aws.amazon.com/vpc/latest/userguide/vpc-nat-gateway.html#)
> Heroku Addons (https://elements.heroku.com/addons#network )
> Both of these approaches should enable the user to provide a static IP address that we can whitelist.
> 
> NOTE: we are not prepared to whitelist the entire range of addresses owned by AWS, Heroku or other cloud providers as the enormity of the list would inadvertently grant access to other parties.
> 
> Alternatively, the standard API may be a suitable choice depending on the style of interaction required. Further examples of the standard API interaction model are here: https://knowledge.opencorporates.com/knowledge-base/api-walkthrough/

**Comment by tiredpixel** [comment]
@spacesnottabs, @StephenAbbott, what is the testing status of this ticket, please?

**Comment by StephenAbbott** [comment]
IP address used by Register for OpenCorporates reconciliation API has been added to the OpenCorporates whitelist and was tested successfully on 26th September 2023. Signing off ✅
