### ISSUE TITLE
Register v2: Support raw records lookup for DK and SK sources

### ISSUE THREAD

**Issue by spacesnottabs** [openownership/register#162]
For our BODS records, it is necessary to be able to link our records to see which original source records produced these records.

For example, see the page below:

https://register.openownership.org/entities/59b978b167e4ebf340844101/raw

This has been implemented for our Register v2 for the PSC source, using the company number and source URL to retrieve the PSC records from the repository in register_sources_psc.

https://github.com/openownership/register-sources-psc/blob/main/lib/register_sources_psc/repositories/company_record_repository.rb

This needs to be updated to also work for records which have come from the DK and SK sources.

**Comment by StephenAbbott** [comment]
Estimate: 8 hours

**Comment by StephenAbbott** [comment]
See pull request for DK raw records work https://github.com/openownership/register-sources-dk/pull/7
