### ISSUE TITLE
Register v2: Fix pagination of search results in Register v2

### ISSUE THREAD

**Issue by spacesnottabs** [openownership/register#163]
After searching for companies using company name or company number from the register-sources-bods repository (BODS v2 records), deduplication is done using the “replacesStatements” to find which statement is the most recent, with the goal of only displaying each company once.

However, this breaks pagination, as we might retrieve the next 10 records, but then only display 5 of them (as the others could be statements which have been replaced). Additionally this makes the count from Elasticsearch incorrect.

It isn’t obvious how to fix this, but the goal should be to have the results per page and total count being correct when searching.

**Comment by StephenAbbott** [comment]
Estimate: 12 hours

**Comment by StephenAbbott** [comment]
Could I ask @kd-ods or @radix0000 to have a look at @tiredpixel's comments above about `replacesStatements` to see what you think from a BODS data modelling perspective?

**Comment by kd-ods** [comment]
I don't think there's much to say from a BODS modelling perspective. I'll leave @radix0000 to comment on the computational efficiency of these options.

**Comment by tiredpixel** [comment]
@spacesnottabs, this is now ready for you to test end-to-end, please. :stars: To do so, please test the following cross-repo PRs simultaneously (`163-pagination` branch on each):

- https://github.com/openownership/register-sources-bods/pull/18
- https://github.com/openownership/register-v2/pull/16
- https://github.com/openownership/register-transformer-psc/pull/17

The last two just update the Gem locks, so if you have a problem checking out the branch like that, you can point register-v2 and register-transformer-psc at local register-sources-bods and check out that branch.

In particular, the following should work:

- import of local data into a new index using register-transformer-psc
- that should contain a new `metadata.replaced` mapping (not that this matters; it isn't actually necessary to update the mappings, here)
- some documents should have `metadata.replaced = true`, and others should have `metadata.replaced = null` (or missing)
- those documents should be the ones replaced by `replacesStatements`
- searching in register-v2 should work (e.g. `xerox`)
- the replaced documents should be excluded
- the total number of results should be correct
- multiple pages should work
- (clicking on a result doesn't work; I believe that's unrelated)

Not considered in this is what to do with existing indexes. By my reasoning, they should continue to work as before (i.e. brokenly) without these patches. Rerunning an import on an existing index *should* work for filling in the `metadata.replaced` field—but only if no duplicate documents are inserted. When I tried this process even without these patches, I still got some extra documents…

cc @StephenAbbott

**Comment by tiredpixel** [comment]
@spacesnottabs and I have completed testing this, and all looks good so far. Everything has been merged, and final tests can now take place during the normal imports over the coming weeks.

**Comment by tiredpixel** [comment]
@StephenAbbott, what is the status of this ticket? Has it passed testing? Is it able to be marked as completed?

**Comment by StephenAbbott** [comment]
@tiredpixel Yes. Has been tested and we're happy - so please mark this as completed

**Comment by tiredpixel** [comment]
Excellent. Thanks.
