### ISSUE TITLE
Upgrade existing Ruby 2.7 Lambda functions to Ruby 3.2

### ISSUE THREAD

**Issue by StephenAbbott** [openownership/register#179]
From AWS:

> We are ending support for Ruby 2.7 in AWS Lambda. This follows Ruby 2.7 End-Of-Life (EOL) reached on March 31, 2023 [1].
> 
> As described in the Lambda runtime support policy [2], end of support for language runtimes in Lambda happens in two stages. Starting December 7, 2023, Lambda will no longer apply security patches and other updates to the Ruby 2.7 runtime used by Lambda functions, and functions using Ruby 2.7 will no longer be eligible for technical support. In addition, you will no longer be able to create new Lambda functions using the Ruby 2.7 runtime. Starting January 25, 2024, you will no longer be able to update existing functions using the Ruby 2.7 runtime.
> 
> We recommend that you upgrade your existing Ruby 2.7 functions to Ruby 3.2 before December 7, 2023.
> 
> End of support does not impact function execution. Your functions will continue to run. However, they will be running on an unsupported runtime which is no longer maintained or patched by the AWS Lambda team.

**Comment by tiredpixel** [comment]
https://github.com/openownership/register/issues/213 will probably render this ticket unnecessary.

**Comment by tiredpixel** [comment]
The new Register Files Combiner in https://github.com/openownership/register/issues/213 renders this unnecessary, since we'll no longer be running Lambda code (as far as I'm aware). I suggest we can close this, @StephenAbbott .
