### ISSUE TITLE
Update README for Register repo following Register v2 changes

### ISSUE THREAD

**Issue by StephenAbbott** [openownership/register#185]
- [x] `register-common` README
- [x] `register-sources-sk` README
- [x] `register-sources-dk` README
- [x] `register-sources-psc` README
- [x] `register-sources-oc` README
- [x] `register-sources-bods` README
- [x] `register-transformer-sk` README
- [x] `register-transformer-dk` README
- [x] `register-transformer-psc` README
- [x] `register-ingester-sk` README
- [x] `register-ingester-dk` README
- [x] `register-ingester-psc` README
- [x] `register-ingester-oc` README
- [x] `register` README

**Comment by tiredpixel** [comment]
These will be updated during this month's bulk data import.

**Comment by tiredpixel** [comment]
@StephenAbbott, I've completed my update of the 14 READMEs. :sweat_smile: Along the way, I ensured all the commands for installation, testing, and usage were up-to-date. I also made various small fixes and improvements along the way, motivated by me handling most of this month's bulk data import. There are certainly more improvements possible, but this should put us in much better shape (and things should work!). Could you please cast your eye over the READMEs, and see if there's anything you'd like to amend or extend? (PRs would be great, if so!) Thanks!

**Comment by StephenAbbott** [comment]
@tiredpixel At first glance, READMEs all look good. Please go ahead and close this ticket and then I can always raise PRs in future if I think of changes to make (not going to get time to do that this week before I'm on leave)
