### ISSUE TITLE
Offer latest Register JSON download via latest URL as well as dated download file

### ISSUE THREAD

**Issue by StephenAbbott** [openownership/register#187]
On the [Downloads page](https://register.openownership.org/download), we offer the latest BODS JSON download file for all the data from the Open Ownership Register. 

This download link is promoted both via the 'Latest data' download button on the right-hand side (when viewed on desktop) and from the Downloads section which links to several of the most recent download files:  
<img width="1378" alt="image" src="https://github.com/openownership/register/assets/1506468/211335dd-d855-42e2-8c81-c8e977bdee64">

In Register v1, we offered this download file both as a dated download file and also offered the latest full JSON file via a latest URL - https://oo-register-production.s3-eu-west-1.amazonaws.com/public/exports/statements.latest.jsonl.gz.

I would like to request that this functionality is replicated for Register v2 so that the 'Latest data' download button on the right-hand side always downloads the latest BODS JSON file while the dated download files are listed/available for download from the Downloads section. 

The new latest URL will likely be different to the one used before following AWS folder changes. This is fine

**Comment by tiredpixel** [comment]
Once the linked PR has been merged, this can be tested.

**Comment by tiredpixel** [comment]
@StephenAbbott, this has been merged and auto-deploy to stg, and is ready for testing.

**Comment by StephenAbbott** [comment]
Thanks @tiredpixel. Happy to approve ✅

**Comment by tiredpixel** [comment]
Thanks for testing, @StephenAbbott .
