### ISSUE TITLE
Set new og:image metadata as a hint for preview-generation on search engines and social media

### ISSUE THREAD

**Issue by StephenAbbott** [openownership/register#205]
I'd like to replace the [current promotional image](https://github.com/openownership/register/blob/2e933af6f6a54d1a9f4703c66e8293eb83fc88ea/app/assets/images/screenshot-network.png) showcased when links to the Open Ownership Register are shared on social media platforms with the image below instead:

![Open Ownership Register](https://github.com/openownership/register/assets/1506468/3196735e-ea5e-49ba-8613-2a3f37b9da77)

This should involve adding og:image metadata as a hint for preview-generation on search engines and social media.

**Comment by tiredpixel** [comment]
@StephenAbbott, this is ready for testing in stg. I suggest you use the LinkedIn Post Inspector:
https://www.linkedin.com/post-inspector/

**Comment by tiredpixel** [comment]
@StephenAbbott, what is the testing status of this ticket?

**Comment by StephenAbbott** [comment]
Signed off ✅

**Comment by tiredpixel** [comment]
Thanks, @StephenAbbott .
