### ISSUE TITLE
Content Markdown not updating site

### ISSUE THREAD

**Issue by tiredpixel** [openownership/register#212]
Some Markdown files in the `content/` directory were updated in 7112520c940da8814aa2c5132553fcbd18e95c2f, but these changes are not reflected on the site (e.g. https://register.openownership.org/data_sources/uk-psc-register). This is because Register 1 used a process to update content, and Register 2 is not using this process.

Rather than update Register 2 to use this process, it would seem better to replace the process with something more standard not requiring additional steps when content is updated.

Based on @spacesnottabs's investigation with me into this:

- [x] change `DataSourceRepository` `all` to parse files in initialiser (or similar) (i.e. https://github.com/openownership/register/blob/master/app/repositories/data_source_repository.rb#L9)
- [x] update the initialiser (or similar) to do the preprocessing, generated from the Markdown files
- [x] remove the `datasources.json` file, which will no longer be needed (and isn't currently getting updated in Register 2 anyway) (i.e. https://github.com/openownership/register/blob/master/app/repositories/datasources.json)

**Comment by StephenAbbott** [comment]
@tiredpixel Adding here that Denmark page - https://register.openownership.org/data_sources/dk-cvr-register - has reverted to old incorrect text with broken links. Correct data availability section which should be showing can be found at https://github.com/openownership/register/blob/master/content/data_sources/dk-cvr-register/data_availability.en.md

**Comment by tiredpixel** [comment]
Thanks for the additional information, @StephenAbbott . I suspect that there may be many similar breakages. We might want to consider the priority of this in the plan; I don't anticipate it being much work, at least compared to many of the other ongoing tickets, but it sounds like it's causing lots of issues. A quick(ish) win, perhaps.

**Comment by StephenAbbott** [comment]
Have moved up the priority list...

**Comment by StephenAbbott** [comment]
Tested on staging and now production - and signed off ✅

**Comment by tiredpixel** [comment]
Thanks, @StephenAbbott .
