### ISSUE TITLE
Update Register to handle alternateNames to support use of field in Armenia's BODS data

### ISSUE THREAD

**Issue by StephenAbbott** [openownership/register#222]
### Summary
BODS v0.2 supports `alternateNames` as a field for entities, but currently that is not populated in OO Register. 

This would be useful, especially when dealing with entities based in other countries with other alphabet systems (e.g. Armenia data ingestion - see https://github.com/openownership/register/issues/171).

One way to do this is by using the OpenCorporates data to populate the field. Additionally, the search functionality should be updated to search `alternateNames`.

For the Armenia data, it is likely that we won't be able to reconcile the data with OpenCorporates due to lack of presence of the Armenian Public Service Number in BODS data - but the `alternateNames` field is present in the Armenia BODS JSON files so this should be retained for use by the OO Register.

## AN1: Ingest bulk data for `alternateNames`

- [x] Ingest the bulk data for alternates names using register-ingester-oc
- [x] Ensure documentation is up to date for performing the import

Note: this will need to be done monthly when importing the companies and additional identifiers bulk data.

Estimate = 0.5 hours

## AN2: Check `alternateNames` Elasticsearch index mapping

- [x] The Elasticsearch mapping is set to be “text” for `alternateNames` https://github.com/openownership/register-sources-bods/blob/main/lib/register_sources_bods/services/mappings/mapping.json#L25

This should also support search arrays of text, but double-check it is correct.

Estimate = 0.5 hours

## AN3: Update data resolver to include `alternateNames`

This is similar to when additional identifiers were included and requires updating the ResolverService in register-sources-oc.

- [x] Update EntityResolver to include the alt_names repository 
- [x] Add this data to the response object
- [x] Update unit tests

Estimate = 3 hours

## AN4: Update Transformers to include `alternateNames` from OpenCorporates

This is similar to when additional identifiers were included. This depends on AN2 and AN3 being done first.

- [x] Add alternateNames as a method in ResolverMappings in register-sources-bods
- [x] Update register-sources-bods in transformers
- [x] Add alternateNames as a field using the method in ResolverMappings in the entity mappers and child_entity mappers (in each transformer, eg PSC, SK, DK)

Estimate = 4 hours

## AN5: Update search functionality to also search alternate names

- [x] As well as searching company number and name fields, the search should also search the alternate names field. This will require updating the EntityQueryBuilder in register-sources-bods.

Estimate = 2 hours

**Comment by tiredpixel** [comment]
### AN3

There is no `EntityResolver`. This is probably supposed to read `ResolverService`, instead.

The response object referenced is probably `ResolverResponse`.

Regarding additional identifiers added previously, see fb3b728661b6c5383a9782ec7b374aff2609611d .

**Comment by tiredpixel** [comment]
@StephenAbbott relayed that OpenCorporates don't have alternate names for GB data. Alternative DK test cases have been identified:

- https://opencorporates.com/companies/dk/38284967
- https://opencorporates.com/companies/dk/92405451
- https://opencorporates.com/companies/dk/89998719

This ticket is unpaused; I'll continue with it soon.

**Comment by tiredpixel** [comment]
Missing from this plan is migrating existing data in Elasticsearch indexes to add the OpenCorporates alternate names data.

### AN6

- [ ] Migrate AM
- [ ] Migrate SK
- [ ] Migrate DK
- [ ] Migrate PSC

**Comment by tiredpixel** [comment]
Alternate names are now available in Register in staging.

Alternate names imported from Open Corporates, present in `alt_names` Elasticsearch index (1 per alternate name, not entity):

- GB:      0
- DK: 318606
- SK:      4
- AM:      0

Statements with at least 1 alternate name, present in `bods_v2_*_prod100` Elasticsearch indexes (ignoring replaced statements):

- PSC:     0
- DK:  68572
- SK:      0
- AM:     52

Statements regardless of alternate names, present in `bods_v2_*_prod100` Elasticsearch indexes (ignoring replaced statements):

- PSC: 29626981
- DK:   1890079
- SK:    277205
- AM:      1041

**Comment by StephenAbbott** [comment]
Tested and signed off ✅

**Comment by tiredpixel** [comment]
Thanks, @StephenAbbott .
