### ISSUE TITLE
Add some ways to browse example data

### ISSUE THREAD

**Issue by stevenday** [openownership/register#24]
This was a recommendation that came out of a UX review commissioned across all of OO's web properties and it has been mentioned by other users too.

The UX review specifically suggested adding example(s) to the homepage, other users have asked for ways to browse by country.

**Comment by StephenAbbott** [comment]
Sample/example data now available via https://bods-data.openownership.org/source/register so closing this issue (although I still need to work on updating the Register website to link to/promote BODS data analysis tools)
