### ISSUE TITLE
PSC-STM-A1: Check licensing agreement for a PSC Stream key

### ISSUE THREAD

**Issue by tiredpixel** [openownership/register#240]
For the prototype, a personal email was used to signup for a PSC Stream key for testing purposes.

Need to check the licensing agreement with Companies House for using their Stream API and to check the standard key offered fits our purposes.

_Estimate: ?_

**Comment by tiredpixel** [comment]
@StephenAbbott, this task is marked as for you, in the PSC Streaming Plan, so I'm assigning it to you to reassign or do whatever is best.

**Comment by StephenAbbott** [comment]
Have confirmed that we should just sign up for a standard key https://developer-specs.company-information.service.gov.uk/streaming-api/guides/authentication

**Comment by tiredpixel** [comment]
Thanks, @StephenAbbott . I think we can mark this as done, then, since signing up for a key is https://github.com/openownership/register/issues/241 .

**Comment by tiredpixel** [comment]
Clarification from PDF about meaning of PSC-STM-A section:

### Part A: Continuous Ingestion

**Goal**
The goal is to replace the PSC Snapshot ingestion with ingesting from the PSC Stream.
