### ISSUE TITLE
You can't submit a state-owned entity because all ownership has to end with a person

### ISSUE THREAD

**Issue by stevenday** [openownership/register#27]
We just had this issue with: https://register.openownership.org/entities/5e569474ac0ca34dfc6841b6 which a submitter had initially corrected/hacked around by putting the president as the president of the state-owned holding company.

**Comment by StephenAbbott** [comment]
Tagging @scatteredink as an FYI on SOEs

**Comment by StephenAbbott** [comment]
We don't yet demonstrate this via the Open Ownership Register but version 0.3 of the Beneficial Ownership Data Standard introduced the ability to capture beneficial ownership networks involving states and state-owned enterprises where the state can be represented as an entity alongside other potential scenarios.

Technical guidance: https://standard.openownership.org/en/0.3.0/schema/guidance/repr-state-owned-enterprises.html
